name: Lighthouse CI

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        form_factor: [desktop,mobile]
    steps:
      - uses: actions/checkout@v3  # Checkout your repository code
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Lighthouse
        run: npm install -g lighthouse lighthouse-cli
      - name: Run Lighthouse scans
        uses: treosh/lighthouse-ci-action@v12  # Consider using treosh/lighthouse-ci-action@v12 for newer Lighthouse versions
        with:
          urls: https://www.applydigital.com/  # Main URL
          configPath: './lighthouserc.json'
          uploadArtifacts: true
          artifactName: lighthouse-results-${{ github.run_id }}-${{ matrix.form_factor }}
      - name: List files
        run: ls -la
      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results-${{ github.run_id }}-${{ matrix.form_factor }}
          path: ./lighthouseci
          retention-days: 10
