name: Lighthouse CI

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        form_factor: [desktop,mobile]
    steps:
      - uses: actions/checkout@v3  # Checkout your repository code
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Set FORM_FACTOR Environment Variable
        run: echo "FORM_FACTOR=${{ matrix.form_factor }}" >> $GITHUB_ENV

      - name: Run Lighthouse CI
        run: lhci autorun --config=./lighthouserc.ci.js
        env:
          FORM_FACTOR: ${{ matrix.form_factor }}

      - name: List files
        run: ls -la ./lighthouseci

      - name: Upload Lighthouse Results Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results-${{ github.run_id }}-${{ matrix.form_factor }}
          path: ./lighthouseci
          retention-days: 10
 