name: Lighthouse CI

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        form_factor: [mobile, desktop]
    steps:
      - uses: actions/checkout@v3  # Checkout your repository code
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Lighthouse
        run: npm install -g lighthouse lighthouse-cli
      - name: Run Lighthouse scans
        uses: treosh/lighthouse-ci-action@v12  # Consider using treosh/lighthouse-ci-action@v12 for newer Lighthouse versions
        with:
          urls: |
            https://www.applydigital.com  # Main URL
            uploadArtifacts: true
          
      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-results
          path: lighthouse*.json  # Matches any Lighthouse JSON report
